---
name: 'prepare'
description: 'Composite action to setup java, gradle, docker'

runs:
  using: "composite"
  steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v4.2.1
      with:
        java-version: 21
        distribution: 'adopt'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: set up docker buildx
      uses: docker/setup-buildx-action@v3