/*
 * Copyright 2020 ConsenSys AG.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 */

package tech.pegasys.teku.ssz.backing.containers;

import tech.pegasys.teku.ssz.backing.ViewRead;
import tech.pegasys.teku.ssz.backing.tree.TreeNode;
import tech.pegasys.teku.ssz.backing.view.AbstractImmutableContainer;

/** Autogenerated by tech.pegasys.teku.ssz.backing.ContainersGenerator */
public class Container1<C extends Container1<C, V0>, V0 extends ViewRead>
    extends AbstractImmutableContainer {

  protected Container1(ContainerType1<C, V0> type) {
    super(type);
  }

  protected Container1(ContainerType1<C, V0> type, TreeNode backingNode) {
    super(type, backingNode);
  }

  protected Container1(ContainerType1<C, V0> type, V0 arg0) {
    super(type, arg0);
  }

  protected V0 getField0() {
    return getAny(0);
  }
}
