/*
 * Copyright Consensys Software Inc., 2022
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 */

package tech.pegasys.teku.infrastructure.ssz.containers;

import java.util.List;
import java.util.function.BiFunction;
import tech.pegasys.teku.infrastructure.ssz.SszData;
import tech.pegasys.teku.infrastructure.ssz.SszStableContainer;
import tech.pegasys.teku.infrastructure.ssz.schema.SszSchema;
import tech.pegasys.teku.infrastructure.ssz.schema.impl.AbstractSszStableProfileSchema;
import tech.pegasys.teku.infrastructure.ssz.tree.TreeNode;

/** Autogenerated by tech.pegasys.teku.ssz.backing.ContainersGenerator */
public abstract class StableProfileSchema1<C extends SszStableContainer, V0 extends SszData>
    extends AbstractSszStableProfileSchema<C> {

  public static <C extends SszStableContainer, V0 extends SszData>
      StableProfileSchema1<C, V0> create(
          final SszSchema<V0> fieldSchema0,
          final int maxFieldCount,
          final BiFunction<StableProfileSchema1<C, V0>, TreeNode, C> instanceCtor) {
    return new StableProfileSchema1<>(fieldSchema0, maxFieldCount) {
      @Override
      public C createFromBackingNode(final TreeNode node) {
        return instanceCtor.apply(this, node);
      }
    };
  }

  protected StableProfileSchema1(final SszSchema<V0> fieldSchema0, final int maxFieldCount) {

    super("", continuousActiveSchemas(List.of(fieldSchema0)), maxFieldCount);
  }

  protected StableProfileSchema1(
      final String containerName,
      final NamedSchema<V0> fieldNamedSchema0,
      final int maxFieldCount) {

    super(containerName, continuousActiveNamedSchemas(List.of(fieldNamedSchema0)), maxFieldCount);
  }

  @SuppressWarnings("unchecked")
  public SszSchema<V0> getFieldSchema0() {
    return (SszSchema<V0>) getChildSchema(0);
  }
}
