dependencies {
	implementation project(':ethereum:spec')
	implementation project(':infrastructure:time')
	implementation project(':infrastructure:unsigned')

	testImplementation project(':ethereum:pow:api')

	testImplementation testFixtures(project(':ethereum:spec'))

	testFixturesImplementation project(':ethereum:pow:api')
	testFixturesImplementation project(':infrastructure:events')
}
