version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10
    working_directory: /tmp/workspace
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - ~/.cache/yarn
      - run: 
          name: Run tests
          command: gradle test
      - persist_to_workspace:
          root: /tmp
          paths:
            - workspace