---
name: 'gather test artifacts'
description: 'Composite action to gather test results and artifacts'

inputs:
  stage_key:
    type: string
    required: true

runs:
  using: "composite"
  steps:
  
    - name: Gather test artifacts
      shell: bash
      run: |
        FILES=`find . -name test-artifacts`
        for FILE in $FILES
        do
          MODULE=`echo "$FILE" | sed -e 's@./\(.*\)/build/test-artifacts@\1@'`
          TARGET="build/test-artifacts/$MODULE"
          mkdir -p "$TARGET"
          cp -rf ${FILE}/*/* "$TARGET"
        done

    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{inputs.stage_key}}-test-artifacts
        path: |
          build/test-artifacts
        retention-days: 1
        if-no-files-found: ignore
