---
name: 'junit results'
description: 'Composite action to gather junit results'

inputs:
  stage_key:
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: Gather junit results
      uses: actions/download-artifact@v4
      with:
        pattern: ${{inputs.stage_key}}-reports-*
        path: reports/${{inputs.stage_key}}
        merge-multiple: true

    - shell: bash
      run: |
        tree reports/

    # https://github.com/dorny/test-reporter
    - name: Test Reporter
      uses: dorny/test-reporter@v2
      env:
        NODE_OPTIONS: "--max_old_space_size=4096"      
      with:
        name: Combined ${{inputs.stage_key}} tests
        path: "reports/${{inputs.stage_key}}/**/TEST-*.xml"
        reporter: java-junit
        only-summary: 'false'
        list-tests: 'failed'
        list-suites: 'failed'
        use-actions-summary: 'true'
        # all/none/failed
