# Mainnet preset - EIP7805
# Inclusion List Committee
# ---------------------------------------------------------------
# 2**4 (= 16)
IL_COMMITTEE_SIZE: 16

# Execution
# ---------------------------------------------------------------
MAX_TRANSACTIONS_PER_INCLUSION_LIST: 1
