# prometheus.yml
global:
  scrape_interval: 5s
  external_labels:
    monitor: 'my-monitor'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'teku1'
    static_configs:
      - targets: ['teku1:8008']
  - job_name: 'teku2'
    static_configs:
      - targets: ['teku2:8008']
  - job_name: 'teku3'
    static_configs:
      - targets: ['teku3:8008']
  - job_name: 'teku4'
    static_configs:
      - targets: ['teku4:8008']