# Mainnet preset - EIP7805
# Inclusion List Committee
# ---------------------------------------------------------------
# 2**4 (= 16)
INCLUSION_LIST_COMMITTEE_SIZE: 16

# Execution
# ---------------------------------------------------------------
MAX_TRANSACTIONS_PER_INCLUSION_LIST: 1
# 2**4
MAX_REQUEST_INCLUSION_LIST: 16
# 2**13
MAX_BYTES_PER_INCLUSION_LIST: 8192
#SECONDS_PER_SLOT * 2 // 3 + 1
VIEW_FREEZE_DEADLINE: 9