# Experimental feature: `Verkle trees` as of https://github.com/ethereum/consensus-specs/pull/3230/
# ---------------------------------------------------------------
# `uint64(2**16)`
MAX_STEMS: 65536
# `uint64(33)`
MAX_COMMITMENTS_PER_STEM: 33
# `uint64(256)`
VERKLE_WIDTH: 256
# `uint64(8)`
IPA_PROOF_DEPTH: 8