---
name: 'gather test results'
description: 'Composite action to gather test results'

inputs:
  stage_key:
    type: string
    required: true

runs:
  using: "composite"
  steps:
  
    - name: Gather test results
      shell: bash
      run: |
        FILES=`find . -name test-results`
        for FILE in $FILES
        do
          MODULE=`echo "$FILE" | sed -e 's@./\(.*\)/build/test-results@\1@'`
          TARGET="build/test-results/$MODULE"
          mkdir -p "$TARGET"
          find ${FILE} -mindepth 2 -maxdepth 2 -print0 | xargs -0 -I{} cp -rf {} $TARGET
        done

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: ${{inputs.stage_key}}-test-results
        path: |
          build/test-results
        retention-days: 1
        if-no-files-found: ignore
