# This is a TOML document. Boom.

[node]
# networkMode options:
# "mock": use MockP2PNetwork
# "rlpx": use RLPxP2PNetwork
# "hobbits": use HobbitsP2PNetwork
networkMode = "hobbits"
identity = "0x02"
networkInterface = "127.0.0.1"
port = 19002
peers = ["hobs://abcf@localhost:19001", "hobs://abcf@localhost:19000","hobs://abcf@localhost:19003"]

[sim]
numValidators = 16
numNodes = 4

# Modify constants in Constants.java
[constants]
SHARD_COUNT = 8
TARGET_COMMITTEE_SIZE = 4
MAX_BALANCE_CHURN_QUOTIENT = 32
MAX_INDICES_PER_SLASHABLE_VOTE = 4096
MAX_EXIT_DEQUEUES_PER_EPOCH = 4
SHUFFLE_ROUND_COUNT = 90
DEPOSIT_CONTRACT_TREE_DEPTH = 32
MIN_DEPOSIT_AMOUNT = 1000000000
MAX_DEPOSIT_AMOUNT = 32000000000
FORK_CHOICE_BALANCE_INCREMENT = 1000000000
EJECTION_BALANCE = 16000000000
GENESIS_FORK_VERSION = 0
GENESIS_SLOT = 4294967296
GENESIS_EPOCH = 536870912
GENESIS_START_SHARD = 0
SECONDS_PER_SLOT = 6
MIN_ATTESTATION_INCLUSION_DELAY = 1
SLOTS_PER_EPOCH = 8
MIN_SEED_LOOKAHEAD = 1
ACTIVATION_EXIT_DELAY = 4
EPOCHS_PER_ETH1_VOTING_PERIOD = 16
SLOTS_PER_HISTORICAL_ROOT = 64
MIN_VALIDATOR_WITHDRAWABILITY_DELAY = 256
PERSISTENT_COMMITTEE_PERIOD = 2048
LATEST_RANDAO_MIXES_LENGTH = 64
LATEST_ACTIVE_INDEX_ROOTS_LENGTH = 64
LATEST_SLASHED_EXIT_LENGTH = 64
BASE_REWARD_QUOTIENT = 32
WHISTLEBLOWER_REWARD_QUOTIENT = 512
ATTESTATION_INCLUSION_REWARD_QUOTIENT = 8
INACTIVITY_PENALTY_QUOTIENT = 16777216
MIN_PENALTY_QUOTIENT = 32
MAX_PROPOSER_SLASHINGS = 16
MAX_ATTESTER_SLASHINGS = 1
MAX_ATTESTATIONS = 128
MAX_DEPOSITS = 16
MAX_VOLUNTARY_EXITS = 16
MAX_TRANSFERS = 16
DOMAIN_BEACON_BLOCK = 0
DOMAIN_RANDAO = 1
DOMAIN_ATTESTATION = 2
DOMAIN_DEPOSIT = 3
DOMAIN_VOLUNTARY_EXIT = 4
DOMAIN_TRANSFER = 5