/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package tech.pegasys.teku.bls.impl.blst.swig;

public class fp12 {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected fp12(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(fp12 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        blstJNI.delete_fp12(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFp6(fp6 value) {
    blstJNI.fp12_fp6_set(swigCPtr, this, fp6.getCPtr(value), value);
  }

  public fp6 getFp6() {
    long cPtr = blstJNI.fp12_fp6_get(swigCPtr, this);
    return (cPtr == 0) ? null : new fp6(cPtr, false);
  }

  public fp12() {
    this(blstJNI.new_fp12(), true);
  }

}
