/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package tech.pegasys.teku.bls.impl.blst.swig;

public class fp6 {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected fp6(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(fp6 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        blstJNI.delete_fp6(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFp2(fp2 value) {
    blstJNI.fp6_fp2_set(swigCPtr, this, fp2.getCPtr(value), value);
  }

  public fp2 getFp2() {
    long cPtr = blstJNI.fp6_fp2_get(swigCPtr, this);
    return (cPtr == 0) ? null : new fp2(cPtr, false);
  }

  public fp6() {
    this(blstJNI.new_fp6(), true);
  }

}
