/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package tech.pegasys.teku.bls.impl.blst.swig;

public class p1 {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected p1(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(p1 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        blstJNI.delete_p1(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setX(fp value) {
    blstJNI.p1_x_set(swigCPtr, this, fp.getCPtr(value), value);
  }

  public fp getX() {
    long cPtr = blstJNI.p1_x_get(swigCPtr, this);
    return (cPtr == 0) ? null : new fp(cPtr, false);
  }

  public void setY(fp value) {
    blstJNI.p1_y_set(swigCPtr, this, fp.getCPtr(value), value);
  }

  public fp getY() {
    long cPtr = blstJNI.p1_y_get(swigCPtr, this);
    return (cPtr == 0) ? null : new fp(cPtr, false);
  }

  public void setZ(fp value) {
    blstJNI.p1_z_set(swigCPtr, this, fp.getCPtr(value), value);
  }

  public fp getZ() {
    long cPtr = blstJNI.p1_z_get(swigCPtr, this);
    return (cPtr == 0) ? null : new fp(cPtr, false);
  }

  public p1() {
    this(blstJNI.new_p1(), true);
  }

}
