/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package tech.pegasys.teku.bls.impl.blst.swig;

public class p1_affine {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected p1_affine(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(p1_affine obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        blstJNI.delete_p1_affine(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setX(fp value) {
    blstJNI.p1_affine_x_set(swigCPtr, this, fp.getCPtr(value), value);
  }

  public fp getX() {
    long cPtr = blstJNI.p1_affine_x_get(swigCPtr, this);
    return (cPtr == 0) ? null : new fp(cPtr, false);
  }

  public void setY(fp value) {
    blstJNI.p1_affine_y_set(swigCPtr, this, fp.getCPtr(value), value);
  }

  public fp getY() {
    long cPtr = blstJNI.p1_affine_y_get(swigCPtr, this);
    return (cPtr == 0) ? null : new fp(cPtr, false);
  }

  public p1_affine() {
    this(blstJNI.new_p1_affine(), true);
  }

}
