/*
 * Copyright 2019 ConsenSys AG.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 */

package tech.pegasys.artemis.bls.hashToG2;

import static tech.pegasys.artemis.bls.hashToG2.Chains.expChain;
import static tech.pegasys.artemis.bls.hashToG2.Chains.h2Chain;
import static tech.pegasys.artemis.bls.hashToG2.Chains.mxChain;
import static tech.pegasys.artemis.bls.hashToG2.Chains.qChain;
import static tech.pegasys.artemis.bls.hashToG2.FP2Immutable.ONE;
import static tech.pegasys.artemis.bls.hashToG2.IetfTools.HKDF_Expand;
import static tech.pegasys.artemis.bls.hashToG2.IetfTools.HKDF_Extract;
import static tech.pegasys.artemis.bls.hashToG2.Util.os2ip_modP;

import java.nio.charset.StandardCharsets;
import org.apache.milagro.amcl.BLS381.FP;
import org.apache.tuweni.bytes.Bytes;

class Helper {

  /**
   * Tests whether the given point lies on the BLS12-381 curve.
   *
   * @param p a JacobianPoint
   * @return true if the point is on the curve, false otherwise
   */
  static boolean isOnCurve(JacobianPoint p) {
    if (p.isInfinity()) {
      return true;
    }

    FP2Immutable x = p.getX();
    FP2Immutable y = p.getY();
    FP2Immutable z = p.getZ();

    FP2Immutable y2 = y.sqr();
    FP2Immutable x3 = x.pow(3);
    FP2Immutable z6 = z.pow(6);

    FP2Immutable four = new FP2Immutable(new FP(4), new FP(4));
    return y2.equals(x3.add(z6.mul(four)));
  }

  /**
   * Tests whether the given point lies in the G2 group.
   *
   * <p>Once the GLV patent has expired we can replace the qChain with the endomorphism here:
   * https://eprint.iacr.org/2019/814.pdf
   *
   * @param p a JacobianPoint
   * @return true if the point is in G2, false otherwise
   */
  static boolean isInG2(JacobianPoint p) {
    return isOnCurve(p) && qChain(p).isInfinity();
  }

  /**
   * Hashes a string msg of any length into an element of the FP2 field.
   *
   * <p>As defined at https://tools.ietf.org/html/draft-irtf-cfrg-hash-to-curve-04#section-5.3
   *
   * <p>This is hash_to_base() in the reference code.
   *
   * @param message the message to hash
   * @param ctr 0, 1, or 2 - used to efficiently create independent instances of hash_to_base
   * @param salt key for the HMAC base hash
   * @return an element in FP2
   */
  static FP2Immutable hashToBase(Bytes message, byte ctr, Bytes salt) {

    final Bytes h2cBytes = Bytes.wrap("H2C".getBytes(StandardCharsets.US_ASCII));
    final Bytes ctrBytes = Bytes.of(ctr);

    Bytes info, t;

    // Do HKDF-Extract
    Bytes m_prime = HKDF_Extract(salt, Bytes.concatenate(message, Bytes.of((byte) 0)));

    // Do first HKDF-Expand
    info = Bytes.concatenate(h2cBytes, ctrBytes, Bytes.of((byte) 1));
    t = HKDF_Expand(m_prime, info, 64);
    FP e1 = os2ip_modP(t);

    // Do second HKDF-Expand
    info = Bytes.concatenate(h2cBytes, ctrBytes, Bytes.of((byte) 2));
    t = HKDF_Expand(m_prime, info, 64);
    FP e2 = os2ip_modP(t);

    return new FP2Immutable(e1, e2);
  }

  /**
   * Calculates a point on the elliptic curve E from an element of the finite field FP2.
   *
   * <p>Curve E here is a curve isogenous to the BLS12-381 curve. Points generated by this function
   * will likely fail the onCurveG2() test.
   *
   * <p>This corresponds to osswu2_help() in the reference code.
   *
   * @param t the input field point
   * @return a point on the isogenous curve
   */
  static JacobianPoint mapToCurve(FP2Immutable t) {

    // First, compute X0(t), detecting and handling exceptional case
    FP2Immutable tPow2 = t.sqr();
    FP2Immutable tPow4 = tPow2.sqr();
    FP2Immutable num_den_common = Consts.xi_2Pow2.mul(tPow4).add(Consts.xi_2.mul(tPow2));
    FP2Immutable x0_num = Consts.Ell2p_b.mul(num_den_common.add(ONE));
    FP2Immutable x0_den = Consts.Ell2p_a.neg().mul(num_den_common);
    if (x0_den.iszilch()) {
      x0_den = Consts.Ell2p_a.mul(Consts.xi_2);
    }

    // Compute num and den of g(X0(t))
    FP2Immutable gx0_den = x0_den.pow(3);
    FP2Immutable gx0_num = Consts.Ell2p_b.mul(gx0_den);
    gx0_num = gx0_num.add(Consts.Ell2p_a.mul(x0_num).mul(x0_den.pow(2)));
    gx0_num = gx0_num.add(x0_num.pow(3));

    // try taking sqrt of g(X0(t))
    // this uses the trick for combining division and sqrt from Section 5 of
    // Bernstein, Duif, Lange, Schwabe, and Yang, "High-speed high-security signatures."
    // J Crypt Eng 2(2):77--89, Sept. 2012. http://ed25519.cr.yp.to/ed25519-20110926.pdf
    FP2Immutable tmp1, tmp2;
    tmp1 = gx0_den.pow(7); // v^7
    tmp2 = gx0_num.mul(tmp1); // u v^7
    tmp1 = tmp1.mul(tmp2).mul(gx0_den); // u v^15
    FP2Immutable sqrt_candidate = tmp2.mul(expChain(tmp1));

    // check if g(X0(t)) is square and return the sqrt if so
    for (FP2Immutable fp2Immutable : Consts.ROOTS_OF_UNITY) {
      FP2Immutable y0 = sqrt_candidate.mul(fp2Immutable);
      if (y0.sqr().mul(gx0_den).equals(gx0_num)) {
        // found sqrt(g(X0(t))). force sign of y to equal sign of t
        if (t.sgn0() != y0.sgn0()) {
          y0 = y0.neg();
        }
        return new JacobianPoint(x0_num.mul(x0_den), y0.mul(x0_den.pow(3)), x0_den);
      }
    }

    // if we've gotten here, then g(X0(t)) is not square. convert srqt_candidate to sqrt(g(X1(t)))
    FP2Immutable x1_num = Consts.xi_2.mul(tPow2).mul(x0_num);
    FP2Immutable x1_den = x0_den;
    FP2Immutable tPow3 = tPow2.mul(t);
    FP2Immutable tPow6 = tPow3.sqr();
    FP2Immutable gx1_num = Consts.xi_2Pow3.mul(tPow6).mul(gx0_num);
    FP2Immutable gx1_den = gx0_den;
    sqrt_candidate = sqrt_candidate.mul(tPow3);
    for (FP2Immutable eta : Consts.etas) {
      FP2Immutable y1 = eta.mul(sqrt_candidate);
      if (y1.sqr().mul(gx1_den).equals(gx1_num)) {
        // found sqrt(g(X1(t))). force sign of y to equal sign of t
        if (t.sgn0() != y1.sgn0()) {
          y1 = y1.neg();
        }
        return new JacobianPoint(x1_num.mul(x1_den), y1.mul(x1_den.pow(3)), x1_den);
      }
    }

    // Should never be reached
    throw new RuntimeException("mapToCurve failed for unknown reasons.");
  }

  /**
   * Transforms a point on the isogenous curve onto a point on the BLS12-381 curve.
   *
   * <p>This function evaluates the isogeny over Jacobian projective coordinates. For details, see
   * Section 4.3 of Wahby and Boneh, "Fast and simple constant-time hashing to the BLS12-381
   * elliptic curve ePrint # 2019/403, https://ia.cr/2019/403.
   *
   * @param p input point on isogenous curve
   * @return output point on BLS12-381
   */
  static JacobianPoint iso3(JacobianPoint p) {

    FP2Immutable x = new FP2Immutable(p.getX());
    FP2Immutable y = new FP2Immutable(p.getY());
    FP2Immutable z = new FP2Immutable(p.getZ());
    FP2Immutable[] mapvals = new FP2Immutable[4];

    // precompute the required powers of Z^2
    final FP2Immutable[] zpows = new FP2Immutable[4];
    zpows[0] = ONE;
    zpows[1] = z.sqr();
    zpows[2] = zpows[1].sqr();
    zpows[3] = zpows[2].mul(zpows[1]);

    // compute the numerator and denominator of the X and Y maps via Horner's rule
    FP2Immutable[] coeffs_z = new FP2Immutable[4];
    for (int idx = 0; idx < Consts.map_coeffs.length; idx++) {
      FP2Immutable[] coeffs = Consts.map_coeffs[idx];
      coeffs_z[0] = coeffs[coeffs.length - 1];
      for (int j = 1; j < coeffs.length; j++) {
        coeffs_z[j] = coeffs[coeffs.length - j - 1].mul(zpows[j]);
      }
      FP2Immutable tmp = coeffs_z[0];
      for (int j = 1; j < coeffs.length; j++) {
        tmp = tmp.mul(x).add(coeffs_z[j]);
      }
      mapvals[idx] = tmp;
    }

    // xden is of order 1 less than xnum, so need to multiply it by an extra factor of Z^2
    mapvals[1] = mapvals[1].mul(zpows[1]);

    // multiply result of Y map by the y-coordinate y / z^3
    mapvals[2] = mapvals[2].mul(y);
    mapvals[3] = mapvals[3].mul(z.pow(3));

    FP2Immutable zz = mapvals[1].mul(mapvals[3]);
    FP2Immutable xx = mapvals[0].mul(mapvals[3]).mul(zz);
    FP2Immutable yy = mapvals[2].mul(mapvals[1]).mul(zz.sqr());

    return new JacobianPoint(xx, yy, zz);
  }

  /**
   * Cofactor clearing.
   *
   * <p>This is compatible with the version given in section 4.1 of Budroni and Pintore, "Efficient
   * hash maps to G2 on BLS curves," ePrint 2017/419 https://eprint.iacr.org/2017/419 NOTE: this
   * impl works for Jacobian projective coordinates without computing an inversion.
   *
   * <p>The current implementation is equivalent to multiplying by h_eff from
   * https://tools.ietf.org/html/draft-irtf-cfrg-hash-to-curve-05#section-8.9.2 This is, in turn,
   * equivalent to the more efficient method using the endomorphism described above. However, the
   * endomorphism is protected in the US by patent 7110538 until the end of 2020. Once that patent
   * has expired, the endomorphism can be implemented here. Commit
   * 95335bd4b1db78bf06d6bf02c906f3973a2677f1 actually contains the endomorphism code, for
   * reference.
   *
   * @param p the point to be transformed to the G2 group
   * @return a corresponding point in the G2 group
   */
  static JacobianPoint clear_h2(JacobianPoint p) {
    JacobianPoint work, work3;

    // h2
    work = h2Chain(p);
    // 3 * h2
    work3 = work.add(work.dbl());
    // 3 * z * h2
    work = mxChain(work3);
    // 3 * z^2 * h2
    work = mxChain(work);
    // 3 * z^2 * h2 - 3 * h2 = 3 * (z^2 - 1) * h2
    work = work.add(work3.neg());

    return work;
  }
}
