/**
 * The DepositContract class is autogenerated from the deposit contract Vyper source using web3j.
 *
 * <p>To generate new versions you will need the compiled binary and ABI files. Follow the <a
 * href="https://github.com/ethereum/eth2.0-specs/tree/v0.11.1/deposit_contract">instructions from
 * the eth2-specs repo</a> to generate these. Then run:
 *
 * <pre>
 * web3j solidity generate -b DepositContract.bin -a DepositContract.abi -o [PATH_TO_TEKU_ROOT]/pow/src/main/java -p tech.pegasys.teku.pow.contract
 * </pre>
 */
package tech.pegasys.teku.pow.contract;
