version: v1.7.0-alpha.2
style: full

specrefs:
  auto_standardize_names: true
  auto_add_missing_entries: true

  files:
    - configs.yml
    - constants.yml
    - containers.yml
    - dataclasses.yml
    - functions.yml
    - presets.yml

  exceptions:
    constants:
      # Not defined as a constant, unnecessary
      - BASIS_POINTS#phase0
      - DOMAIN_APPLICATION_MASK
      - ENDIANNESS

      # Constants for max values, defined elsewhere
      - UINT256_MAX
      - UINT64_MAX
      - UINT64_MAX_SQRT

      # No light client support
      - MAX_REQUEST_LIGHT_CLIENT_UPDATES

      # Constants in the KZG library
      - BYTES_PER_COMMITMENT
      - BYTES_PER_PROOF
      - FIAT_SHAMIR_PROTOCOL_DOMAIN
      - G1_POINT_AT_INFINITY
      - G2_POINT_AT_INFINITY
      - KZG_ENDIANNESS
      - KZG_SETUP_G2_LENGTH
      - KZG_SETUP_G2_MONOMIAL
      - PRIMITIVE_ROOT_OF_UNITY
      - RANDOM_CHALLENGE_KZG_BATCH_DOMAIN
      - RANDOM_CHALLENGE_KZG_CELL_BATCH_DOMAIN

      # Not implemented: gloas
      - PTC_TIMELINESS_INDEX#gloas
      - NUM_BLOCK_TIMELINESS_DEADLINES#gloas
      - DOMAIN_PROPOSER_PREFERENCES#gloas
      - ATTESTATION_TIMELINESS_INDEX#gloas
      - PAYLOAD_STATUS_EMPTY#gloas
      - PAYLOAD_STATUS_FULL#gloas
      - PAYLOAD_STATUS_PENDING#gloas

    containers:
      # Not defined, unnecessary
      - Eth1Block

      # No light client support
      - LightClientFinalityUpdate
      - LightClientHeader#capella
      - LightClientOptimisticUpdate
      - LightClientBootstrap#capella
      - LightClientUpdate#capella

      # Not implemented: gloas
      - ForkChoiceNode#gloas
      - ProposerPreferences#gloas
      - SignedProposerPreferences#gloas

    dataclasses:
      # Not defined, implemented differently
      - LatestMessage
      - OptimisticStore
      - Store

      # No light client support
      - LightClientStore

    functions:
      # Functions implemented by KZG library for EIP-4844
      - bit_reversal_permutation#deneb
      - blob_to_kzg_commitment#deneb
      - blob_to_polynomial#deneb
      - bls_field_to_bytes#deneb
      - bytes_to_bls_field#deneb
      - bytes_to_kzg_commitment#deneb
      - bytes_to_kzg_proof#deneb
      - compute_blob_kzg_proof#deneb
      - compute_challenge#deneb
      - compute_kzg_proof#deneb
      - compute_kzg_proof_impl#deneb
      - compute_powers#deneb
      - compute_quotient_eval_within_domain#deneb
      - compute_roots_of_unity#deneb
      - evaluate_polynomial_in_evaluation_form#deneb
      - g1_lincomb#deneb
      - hash_to_bls_field#deneb
      - is_power_of_two#deneb
      - reverse_bits#deneb
      - validate_kzg_g1#deneb
      - verify_blob_kzg_proof#deneb
      - verify_blob_kzg_proof_batch#deneb
      - verify_kzg_proof#deneb
      - verify_kzg_proof_batch#deneb
      - verify_kzg_proof_impl#deneb

      # Functions implemented by KZG library for EIP-7594
      - _fft_field#fulu
      - add_polynomialcoeff#fulu
      - cell_to_coset_evals#fulu
      - compute_cells#fulu
      - compute_cells_and_kzg_proofs#fulu
      - compute_cells_and_kzg_proofs_polynomialcoeff#fulu
      - compute_kzg_proof_multi_impl#fulu
      - compute_verify_cell_kzg_proof_batch_challenge#fulu
      - construct_vanishing_polynomial#fulu
      - coset_evals_to_cell#fulu
      - coset_fft_field#fulu
      - coset_for_cell#fulu
      - coset_shift_for_cell#fulu
      - divide_polynomialcoeff#fulu
      - evaluate_polynomialcoeff#fulu
      - fft_field#fulu
      - interpolate_polynomialcoeff#fulu
      - multiply_polynomialcoeff#fulu
      - polynomial_eval_to_coeff#fulu
      - recover_cells_and_kzg_proofs#fulu
      - recover_polynomialcoeff#fulu
      - vanishing_polynomialcoeff#fulu
      - verify_cell_kzg_proof_batch#fulu
      - verify_cell_kzg_proof_batch_impl#fulu

      # No light client support
      - apply_light_client_update
      - block_to_light_client_header
      - compute_sync_committee_period_at_slot
      - create_light_client_bootstrap
      - create_light_client_finality_update
      - create_light_client_optimistic_update
      - create_light_client_update
      - current_sync_committee_gindex_at_slot
      - finalized_root_gindex_at_slot
      - get_lc_execution_root
      - get_safety_threshold
      - get_subtree_index
      - initialize_light_client_store
      - is_better_update
      - is_finality_update
      - is_next_sync_committee_known
      - is_sync_committee_update
      - is_valid_light_client_header
      - is_valid_normalized_merkle_branch
      - next_sync_committee_gindex_at_slot
      - process_light_client_finality_update
      - process_light_client_optimistic_update
      - process_light_client_store_force_update
      - process_light_client_update
      - upgrade_lc_bootstrap_to_capella
      - upgrade_lc_bootstrap_to_deneb
      - upgrade_lc_bootstrap_to_electra
      - upgrade_lc_finality_update_to_capella
      - upgrade_lc_finality_update_to_deneb
      - upgrade_lc_finality_update_to_electra
      - upgrade_lc_header_to_capella
      - upgrade_lc_header_to_deneb
      - upgrade_lc_header_to_electra
      - upgrade_lc_optimistic_update_to_capella
      - upgrade_lc_optimistic_update_to_deneb
      - upgrade_lc_optimistic_update_to_electra
      - upgrade_lc_store_to_capella
      - upgrade_lc_store_to_deneb
      - upgrade_lc_store_to_electra
      - upgrade_lc_update_to_capella
      - upgrade_lc_update_to_deneb
      - upgrade_lc_update_to_electra
      - validate_light_client_update

      # Still need to implement this for Electra
      - compute_weak_subjectivity_period#electra

      # Not implemented: phase0
      - check_if_validator_active#phase0
      - compute_new_state_root#phase0
      - compute_pulled_up_tip#phase0
      - filter_block_tree#phase0
      - get_aggregate_and_proof#phase0
      - get_aggregate_signature#phase0
      - get_attestation_deltas#phase0
      - get_attesting_balance#phase0
      - get_checkpoint_block#phase0
      - get_current_store_epoch#phase0
      - get_eligible_validator_indices#phase0
      - get_filtered_block_tree#phase0
      - get_forkchoice_store#phase0
      - get_head#phase0
      - get_inactivity_penalty_deltas#phase0
      - get_inclusion_delay_deltas#phase0
      - get_matching_head_attestations#phase0
      - get_matching_source_attestations#phase0
      - get_matching_target_attestations#phase0
      - get_slots_since_genesis#phase0
      - get_unslashed_attesting_indices#phase0
      - get_voting_source#phase0
      - is_candidate_block#phase0
      - is_finalization_ok#phase0
      - is_proposer#phase0
      - on_tick_per_slot#phase0
      - seconds_to_milliseconds#phase0
      - store_target_checkpoint_state#phase0
      - update_latest_messages#phase0
      - update_unrealized_checkpoints#phase0
      - validate_target_epoch_against_current_time#phase0
      - xor#phase0
      - compute_proposer_score#phase0
      - get_attestation_score#phase0
      - is_proposer_equivocation#phase0
      - record_block_timeliness#phase0
      - update_proposer_boost_root#phase0

      # Not implemented: altair
      - compute_subnets_for_sync_committee#altair
      - get_contribution_and_proof#altair
      - get_index_for_new_validator#altair
      - get_sync_committee_message#altair
      - get_sync_committee_selection_proof#altair
      - get_sync_subcommittee_pubkeys#altair
      - process_justification_and_finalization#altair
      - process_rewards_and_penalties#altair
      - process_slashings#altair
      - process_sync_committee_contributions#altair
      - set_or_append_list#altair
      - compute_merkle_proof#altair

      # Not implemented: bellatrix
      - get_execution_payload#bellatrix
      - get_pow_block_at_terminal_total_difficulty#bellatrix
      - get_terminal_pow_block#bellatrix
      - is_execution_block#bellatrix
      - is_optimistic_candidate_block#bellatrix
      - is_valid_terminal_pow_block#bellatrix
      - latest_verified_ancestor#bellatrix
      - prepare_execution_payload#bellatrix
      - process_slashings#bellatrix

      # Not implemented: capella
      - prepare_execution_payload#capella
      - process_execution_payload#capella

      # Not implemented: deneb
      - compute_signed_block_header#deneb
      - get_blob_sidecars#deneb
      - prepare_execution_payload#deneb
      - process_registry_updates#deneb
      - process_voluntary_exit#deneb

      # Not implemented: electra
      - add_validator_to_registry#electra
      - compute_on_chain_aggregate#electra
      - get_committee_indices#electra
      - get_eth1_pending_deposit_count#electra
      - is_within_weak_subjectivity_period#electra
      - normalize_merkle_branch#electra
      - prepare_execution_payload#electra
      - process_execution_payload#electra
      - process_voluntary_exit#electra
      - is_eligible_for_partial_withdrawals#electra
      - get_validators_sweep_withdrawals#electra

      # Not implemented: fulu
      - compute_matrix#fulu
      - get_data_column_sidecars#fulu
      - get_data_column_sidecars_from_block#fulu
      - get_data_column_sidecars_from_column_sidecar#fulu
      - recover_matrix#fulu

      # Not implemented: gloas
      - get_aggregate_due_ms#gloas
      - get_ancestor#gloas
      - get_attestation_due_ms#gloas
      - get_attestation_participation_flag_indices#gloas
      - get_checkpoint_block#gloas
      - get_contribution_due_ms#gloas
      - get_data_column_sidecars#gloas
      - get_data_column_sidecars_from_block#gloas
      - get_data_column_sidecars_from_column_sidecar#gloas
      - get_execution_payload_bid_signature#gloas
      - get_execution_payload_envelope_signature#gloas
      - get_expected_withdrawals#gloas
      - get_forkchoice_store#gloas
      - get_head#gloas
      - get_node_children#gloas
      - get_parent_payload_status#gloas
      - get_payload_attestation_message_signature#gloas
      - get_payload_status_tiebreaker#gloas
      - get_ptc_assignment#gloas
      - get_sync_message_due_ms#gloas
      - get_weight#gloas
      - is_merge_transition_complete#gloas
      - is_parent_node_full#gloas
      - is_payload_timely#gloas
      - is_supporting_vote#gloas
      - notify_ptc_messages#gloas
      - on_block#gloas
      - on_execution_payload#gloas
      - on_payload_attestation_message#gloas
      - prepare_execution_payload#gloas
      - process_attestation#gloas
      - process_block#gloas
      - process_proposer_slashing#gloas
      - process_slot#gloas
      - should_extend_payload#gloas
      - update_latest_messages#gloas
      - validate_merge_block#gloas
      - validate_on_attestation#gloas
      - verify_data_column_sidecar#gloas
      - get_attestation_score#gloas
      - get_proposer_preferences_signature#gloas
      - get_upcoming_proposal_slots#gloas
      - is_head_late#gloas
      - is_head_weak#gloas
      - is_parent_strong#gloas
      - is_valid_proposal_slot#gloas
      - process_voluntary_exit#gloas
      - record_block_timeliness#gloas
      - should_apply_proposer_boost#gloas
      - update_proposer_boost_root#gloas
      - is_data_available#gloas
      - verify_data_column_sidecar_kzg_proofs#gloas
