name: "Validate Gradle Wrapper"
on:
  push:
    paths:
      - 'gradle/wrapper/**'
      - 'gradlew'
      - 'gradlew.bat'
  pull_request:
    paths:
      - 'gradle/wrapper/**'
      - 'gradlew'
      - 'gradlew.bat'

permissions:
  contents: read

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      
      - uses: gradle/actions/wrapper-validation@ed408507eac070d1f99cc633dbcf757c94c7933a # v4
