name: Teku PeerDAS acceptance tests

on: pull_request

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: DAS acceptance tests
        run: ./gradlew --no-daemon --parallel acceptance-test:acceptanceTest --tests tech.pegasys.teku.test.acceptance.das*

      - name: Upload results to path
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: acceptance-test-results
          path: ${{ github.workspace }}/acceptance-tests/build/reports/tests/acceptanceTest
          if-no-files-found: ignore
