name: renovatebot

on:
  schedule:
    - cron: "15 3 14,28 * *"
  push:
    branches:
      - master
    paths:
      - '.github/workflows/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  renovatebot-check:
    runs-on: ubuntu-24.04
    environment: security
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Run renovatebot
        uses: ConsenSys/github-actions/renovatebot@8e207ec2ad53d90ab419d39d03084fa93e04d190 # main
        with:
          GH_APP_ID: ${{ secrets.GH_APP_ID }}
          GH_PRIVATE_KEY: ${{ secrets.GH_PRIVATE_KEY }}
          GH_REPOSITORY: ${{ github.repository }}
