name: renovatebot

on:
  schedule:
    - cron: "15 3 14,28 * *"
  push:
    branches:
      - master
    paths:
      - '.github/workflows/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  renovatebot-check:
    runs-on: ubuntu-24.04
    environment: security
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Run renovatebot
        uses: ConsenSys/github-actions/renovatebot@31dbb917dd78b1dc18b4838a2d7d598b359b834f # main
        with:
          GH_APP_ID: ${{ secrets.GH_APP_ID }}
          GH_PRIVATE_KEY: ${{ secrets.GH_PRIVATE_KEY }}
          GH_REPOSITORY: ${{ github.repository }}
