name: "Test Path Check"
on:
  push:
    paths:
      - '**/*.java'
      - 'scripts/testcheck.sh'
  pull_request:
    paths:
      - '**/*.java'
      - 'scripts/testcheck.sh'

permissions:
  contents: read

jobs:
  check:
    name: "Check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Check test paths
        run: ./scripts/testcheck.sh
