name: "Test Path Check"
on:
  push:
    paths:
      - '**/*.java'
      - 'scripts/testcheck.sh'
  pull_request:
    paths:
      - '**/*.java'
      - 'scripts/testcheck.sh'

permissions:
  contents: read

jobs:
  check:
    name: "Check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Check test paths
        run: ./scripts/testcheck.sh
