name: "Test Path Check"
on: [push, pull_request]

jobs:
  check:
    name: "Check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check test paths
        run: ./scripts/testcheck.sh